# Generated by Django 5.1.6 on 2025-03-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_muscle_alter_exercise_muscle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.DeleteModel(
            name='Muscle',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
