# Generated by Django 5.1.6 on 2025-03-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='trainingexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='trainingexercise',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='training',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='weight',
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField(default=0.0)),
                ('training_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.trainingexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
        ),
    ]
